apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
  namespace: production
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: 805724738913.dkr.ecr.us-west-1.amazonaws.com/github_actions_images:latest
          ports:
            - containerPort: 8080
            # Port on which Node.js application listens
            #
          env:
            - name: MY_SECRET
              valueFrom:
               secretKeyRef:
                name: my-secret
                key: my-secret-key
