name: Build Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build artifacts
        run: npm run build

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: path/to/artifacts
